conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls', namespace="pages")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('products/', include('products.urls', namespace="products")),
    path('orders/', include('orders.urls', namespace="orders")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'conf.views.handler404'
# handler401 = 'conf.views.handler404'
# handler403 = 'conf.views.handler404'
# handler500 = 'conf.views.handler404'

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('cart/<int:pk>/', views.add_or_remove, name='add-or-remove'),
    path('cart/', views.UserCartView.as_view(), name='cart'),
    path('order/', views.OrderCreateView.as_view(), name='order'),
]

templates/ordering/cart.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Cart{% endblock %}
{% block body_class %}product-cart checkout-cart{% endblock %}
{% block content %}
    <div class="main-content" id="cart">
        <!-- main -->
        <div id="wrapper-site">
            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Shopping Cart</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <section id="main">
                            <div class="cart-grid row">
                                <div class="col-md-9 col-xs-12 check-info">
                                    <h1 class="title-page">Shopping Cart</h1>
                                    <div class="cart-container">
                                        <div class="cart-overview js-cart">
                                            <ul class="cart-items">

                                                {% for product in products %}

                                                <li class="cart-item">
                                                    <div class="product-line-grid row justify-content-between">
                                                        <!--  product left content: image-->
                                                        <div class="product-line-grid-left col-md-2">
                                                            <span class="product-image media-middle">
                                                                <a href="../products/product-detail.html">
                                                                    <img class="img-fluid" src="{{ product.image1.url }}"
                                                                         alt="Organic Strawberry Fruits">
                                                                </a>
                                                            </span>
                                                        </div>
                                                        <div class="product-line-grid-body col-md-6">
                                                            <div class="product-line-info">
                                                                <a class="label" href="../products/product-detail.html"
                                                                   data-id_customization="0">{{ product.name }}</a>
                                                            </div>
                                                            <div class="product-line-info product-price">
                                                                <span class="value">£{{ product.price }}</span>
                                                            </div>
                                                            <div class="product-line-info">
                                                                <span class="label-atrr">Size:</span>
                                                                <span class="value">S</span>
                                                            </div>
                                                            <div class="product-line-info">
                                                                <span class="label-atrr">Color:</span>
                                                                <span class="value">Blue</span>
                                                            </div>
                                                        </div>
                                                        <div class="product-line-grid-right text-center product-line-actions col-md-4">
                                                            <div class="row">
                                                                <div class="col-md-5 col qty">
                                                                    <div class="label">Qty:</div>
                                                                    <div class="quantity">
                                                                        <input type="text" name="qty" value="1"
                                                                               class="input-group form-control">

                                                                        <span class="input-group-btn-vertical">
                                                                            <button class="btn btn-touchspin js-touchspin bootstrap-touchspin-up"
                                                                                    type="button">
                                                                                +
                                                                            </button>
                                                                            <button class="btn btn-touchspin js-touchspin bootstrap-touchspin-down"
                                                                                    type="button">
                                                                                -
                                                                            </button>
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-5 col price">
                                                                    <div class="label">Total:</div>
                                                                    <div class="product-price total">
                                                                        £{{ product.price }}
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-2 col text-xs-right align-self-end">
                                                                    <div class="cart-line-product-actions ">
                                                                        <a class="remove-from-cart" rel="nofollow"
                                                                           href="{% url 'orders:add-or-remove' pk=product.pk %}?next={{ request.path }}" data-link-action="delete-from-cart"
                                                                           data-id-product="1">
                                                                            <i class="fa fa-trash-o"
                                                                               aria-hidden="true"></i>
                                                                        </a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                    <a href="{% url 'orders:order' %}" class="continue btn btn-primary pull-xs-right">
                                        Continue
                                    </a>
                                </div>
                                <div class="cart-grid-right col-xs-12 col-lg-3">
                                    <div class="cart-summary">
                                        <div class="cart-detailed-totals">
                                            <div class="cart-summary-products">
                                                <div class="summary-label">There are 3 item in your cart</div>
                                            </div>
                                            <div class="cart-summary-line" id="cart-subtotal-products">
                                                <span class="label js-subtotal">
                                                    Total products:
                                                </span>
                                                <span class="value">£200.00</span>
                                            </div>
                                            <div class="cart-summary-line" id="cart-subtotal-shipping">
                                                <span class="label">
                                                    Total Shipping:
                                                </span>
                                                <span class="value">Free</span>
                                                <div>
                                                    <small class="value"></small>
                                                </div>
                                            </div>
                                            <div class="cart-summary-line cart-total">
                                                <span class="label">Total:</span>
                                                <span class="value">£200.00 (tax incl.)</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="block-reassurance">
                                        <ul>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check1.png' %}"
                                                         alt="Security policy (edit with Customer reassurance module)">
                                                    <span>Security policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check2.png' %}"
                                                         alt="Delivery policy (edit with Customer reassurance module)">
                                                    <span>Delivery policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check3.png' %}"
                                                         alt="Return policy (edit with Customer reassurance module)">
                                                    <span>Return policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}